[package]
name = "rust"
version = "0.1.0"
authors = ["SericaLaw <943914044@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = { version = "1.3", features = ["spin_no_std"] }
spin = "0.3"